### ISSUE TITLE
support jasmine/karma

### ISSUE THREAD

**Issue by JostCrow** [g3offrey/javascript-test-runner#1]

**Comment by g3offrey** [comment]
Hi @JostCrow, thank you very much for this feedback 👍 

I'm not an user of jasmine / karma so I have to do some research to resolve this "issue".
However I added your request to my release map 👌 

I'll let you know here once I added support for your frameworks 😄 
Thank you.

**Comment by alimbada** [comment]
@JostCrow I found this issue whilst searching for the same thing, but I've found that there is a dedicated extension for running Jasmine tests here: https://github.com/hbenl/vscode-jasmine-test-adapter.

**Comment by garyhammett** [comment]
Yes that runs jasmine tests when you have a jasmine config, but while using karma it cannot detect the tests.. is there any update on this? Likely to get investigated?

**Comment by alimbada** [comment]
@garyhammett Yes, sorry, I realised that afterwards too.

**Comment by garyhammett** [comment]
It's such a desirable idea to get Karma Jasmine tests working; If i understood it a bit more I would fork and create a pull request.

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
