### ISSUE TITLE
Support multi root workspaces

### ISSUE THREAD

**Issue by roggenbrot** [g3offrey/javascript-test-runner#15]
Current implementation fails on executing/debug test since it will always use the first workspace project as root.

It seems that vscode code passes a string instead of a `WorkspaceFolder` to `getTestRunner`.

This will cause `debug.startDebugging` to always use cwd of the first workspace folder in multi root workspaces.

**Comment by g3offrey** [comment]
Hi @roggenbrot,
again thank you for your help, you seem pretty active on this repo. Your help is really valuable I love that ! 🎉

Indeed this is a very important issue and I checked the pull request you made ! Good job for the fix 👍

Sadly I worked on my side for windows support these last days and I just created the PR, I refactored some code using the `rootPath`. Merging one of the PR would cause conflicts. 

Would it be ok for you If I cherrypick some of your commits as they are still really valuable and close the pull request ? 😅

**Comment by roggenbrot** [comment]
Sure, no problem. Should i test your changes against multi root workspaces?

**Comment by g3offrey** [comment]
Thank you 👍 
If you wanna try it out you can with the #14 branch however I already tested it with a multi root workspaces which didn't work previous to your fix 😄 

I'll merge it tomorrow evening and will release a new version.

**Comment by roggenbrot** [comment]
Debugging with your branch still fails in multi root environments:

### Setup

Workspace with 3 root folders:

- admin
- core
- user

Workspace confif:

```json
{
    "folders": [
        {
            "path": "admin"
        },
        {
            "path": "core"
        },
        {
            "path": "user"
        }
    ]
}
```

### Steps to reproduce

Execute "Debug test" of any jest test case in in folder `core`

### Result

```
[xxxxx@xxxxxxx core]$ cd /home/xxx/admin ; env "NODE_ENV=test" /usr/bin/node --inspect-brk=48087 node_modules/.bin/jest src/form/__tests__/JsonForm.validate.spec.ts --testNamePattern "invalid text schema validation" --runInBand --coverage=false
Debugger listening on ws://127.0.0.1:48087/4fbcd649-e74b-4987-adcd-407b9bb667a4
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
● Validation Error:

  Module <rootDir>/test-shim.js in the setupFiles option was not found.
         <rootDir> is: /home/xxxxxxx/admin

  Configuration Documentation:
  https://jestjs.io/docs/configuration.html

Waiting for the debugger to disconnect...
Killed
```

### Expected behavior


Test should be executed in folder `core`, not `admin`

**Comment by roggenbrot** [comment]
Added comments to your pull requests

**Comment by g3offrey** [comment]
I just pushed a new commit which should resolve this use case thank you for your time 😄
