### ISSUE TITLE
Debug single test does not work

### ISSUE THREAD

**Issue by roggenbrot** [g3offrey/javascript-test-runner#17]
When trying to debug a single Jest test, the debugger will not stop on any breakpoint.

This seems to be either a limitation in Jest or ts-jest transformer since the same problem also occurs when trying to debug a test file with `--testNamePattern` option from command line. Not sure if this is typescript specific problem or if this problem also occurs with pure javascript or if debugging with `--testNamePattern` option is possible at all.

Maybe the `Debug Test` option should be just enabled on test suites

**Comment by roggenbrot** [comment]
After some more investigation this seems to be a typescript only problem.

Breakpoints in typescript files just work for me if coverage is disabled (e.g. --coverage=false CLI option), without `--testNamePattern` CLI option and the following settings in `tsconfig.json`

```
    "module": "commonjs",
    "jsx": "react",
    "target": "es5",
    "esModuleInterop": true,

```

and the following launch configuration

```json
{
    "type": "node",
    "request": "launch",
    "sourceMaps": true,
    "protocol": "inspector",
    "name": "Jest All",
    "program": "${workspaceFolder}/node_modules/.bin/jest",
    "args": [
        "--runInBand",
        "--coverage=false"
    ],
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen",
    "windows": {
        "program": "${workspaceFolder}/node_modules/jest/bin/jest",
    }
}        

```
When using `--testNamePattern` CLI option i was not able to add working breakpoints.

There seems to be a problem with ts-jest and source maps (kulshekhar/ts-jest#114). I will try to find a working configuration/workaround for this problem and then submit a wiki entry with all required configurations or a pull request.

**Comment by roggenbrot** [comment]
Found the real cause now:

Source maps in ts-jest ^23.0.1 are completely broken. After a rollback to 22.4.6 everything works ~~without any additional CLI option or custom tsconfig.json~~ when test coverage is disabled (kulshekhar/ts-jest#334).

Disable coverage via `settings.json`:

```
 "javascript-test-runner.additionalArgs": "--coverage=false"
```

Working `jest config`:

```json
"jest": {
    "setupFiles": [
      "<rootDir>/test-shim.js",
      "<rootDir>/test-setup.js"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    "testPathIgnorePatterns": [
      "/dist/",
      "/node_modules/"
    ],
    "collectCoverage": true
},

```

**Comment by villelahdenvuo** [comment]
@roggenbrot Thank you for your comment. I was also struggling with broken sourcemaps, but disabling coverage made them work! I'm using Jest 24.5.0.
