### ISSUE TITLE
javascript-test-runner.envVars missing

### ISSUE THREAD

**Issue by greenlikeorange** [g3offrey/javascript-test-runner#19]
In my project, I need to add some env variable on running test cases.
When I looking into `javascript-test-runner/package.json` I found `javascript-test-runner.envVars` under `contributes.configuration` that gonna be useful to me.  

On market extension `javascript-test-runner.envVars` is missing.
<img width="1291" alt="screen shot 2018-07-22 at 11 24 02 am" src="https://user-images.githubusercontent.com/4847843/43042385-76464aac-8da2-11e8-8dbf-7707b4be758b.png">
<img width="1040" alt="screen shot 2018-07-22 at 11 38 04 am" src="https://user-images.githubusercontent.com/4847843/43042440-b9266572-8da3-11e8-8f77-633ba6e38934.png">

But I can get this by fork ur repo and build my own
<img width="1035" alt="screen shot 2018-07-22 at 11 35 17 am" src="https://user-images.githubusercontent.com/4847843/43042433-767e8876-8da3-11e8-98c5-29745b375609.png">

And can u please add that configuration on README.

**Comment by g3offrey** [comment]
Hi @greenlikeorange 

thank you for opening a ticket.

This is normal, the version deployed on the marketplace is not the latest on this repo.
I'll try to release the new version including this feature in less than 48 hours 👌
