### ISSUE TITLE
Improve test case detection

### ISSUE THREAD

**Issue by roggenbrot** [g3offrey/javascript-test-runner#22]
At the moment every file is parsed to detect if it's a mocha or jest test case (Token based detection).

Maybe it would be better to parse just files that fulfill the criteria of the framework:

### Mocha

Mocha expects tests normally in folder `test. Instead parsing all files, only files located in a sub folder of `test`could be parsed.

Since it's possible to change the default folder location with a CLI option it should be possible to configure this path.

### Jest

Tests are found by Jest by matching files against a configured regex in either

- [testMatch](https://jestjs.io/docs/en/configuration.html#testmatch-array-string)
or
- [testRegex](https://jestjs.io/docs/en/configuration.html#testregex-string)

This options can set in `package.json`, `jest.config.js` file or or through the `--config <path/to/js|json>` CLI option.

`jest --showConfig` will return the current active configuration as JSON string.

### Further improvements

Maybe parsing should also just be activated if a devDependency to mocha or jest exists in `package.json` (Or if file mocha/jest exists in `node_modules/.bin`).

It should be possible to deactivate this detection by config option to support also environments with global installed mocha/jest

**Comment by g3offrey** [comment]
This sounds really great ! 👍 
I didn't take any time to improve performance for the moment, but love your solution.
I think I took the problem on the wrong side, parsing all files and then deciding if test are from mocha or jest. 

I think your solution parsing `package.json` to test if mocha or jest is present is a good one to increase performance easily. Then as you said we should extract the regexp used by the test runner to get the files to parse. 👍 

This is a lot of work but sounds promising ! I definitely add it to the roadmap 😄 

Thank you for sharing this with me ! 💯

**Comment by lonix1** [comment]
Please also support cypress

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
