### ISSUE TITLE
Jest/Mocha conditional code snippets/completion

### ISSUE THREAD

**Issue by roggenbrot** [g3offrey/javascript-test-runner#25]
#22 will introduce the possibility to detect if a file will be picked up by Jest/Mocha during test execution.

It would be great if this feature could be used to add conditional code snippet/completion for mocha/jest functions like in [this](https://github.com/andys8/vscode-jest-snippets) project, but with the difference that this code snippets would be just enabled for real test files, and not on every javascript file

| Trigger      | Content |
| -------:     | ------- |
| `desc→`      | describe |
| `desco→`     | describe.only |
| `descs→`     | describe.skip |
| `ae→`        | after each |
| `aa→`        | after all |
| `be→`        | before each |
| `ba→`        | before all |
| `it→`        | it |
| `ito→`       | it.only |
| `its→`       | it.skip |
| `ita→`       | it(..., async ...) |
| `test→`      | test |
| `testo→`     | test.only |
| `tests→`     | test.skip |
| `testa→`     | test(..., async ...) |

**Comment by g3offrey** [comment]
Hi @roggenbrot 

I saw the #24 you did a pretty good job, thank you very much 👍
 (for your XXth contributions in a row I bet you deserve a 🥇) 

Concerning snippets I'm sorry but I think we should concentrate our efforts on test runner as I'm not sure that people installing a test runner extension would like to have their intellisense proposing snippets by default (at least for the moment) 😞 

However if you want to take your chance, feel free to fork this repository to build an awesome snippet extension, I'll be glad to install it 😛
