### ISSUE TITLE
Cannot find module paths

### ISSUE THREAD

**Issue by gmukul01** [g3offrey/javascript-test-runner#26]
Hi Team, 

The plugin is not able to identify paths.

I have given below config also in jest.config.js

` modulePaths: ["./src/js", "./src", "./__tests__"]`

And when I add below line in tests, the plugin is not able to identify the module.
`import ActionBar from "containers/ActionBar";`

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
