### ISSUE TITLE
Not working with nx angular use cases

### ISSUE THREAD

**Issue by Jonatthu** [g3offrey/javascript-test-runner#28]
Repro: https://github.com/Jonatthu/nx-angular-test

Is there a way to make it work?

it says the following:
![image](https://user-images.githubusercontent.com/3742176/46898045-5c326900-ce3b-11e8-8c8a-e28af06e3193.png)

But I do have jest installed:
![image](https://user-images.githubusercontent.com/3742176/46898061-7d935500-ce3b-11e8-9666-bcfd926bc084.png)

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
