### ISSUE TITLE
No test runner in your project. Please install one.

### ISSUE THREAD

**Issue by MrHIDEn** [g3offrey/javascript-test-runner#29]
I have `mocha` already installed and working well.
Why do i get message `No test runner in your project. Please install one.`?

**Comment by zpc7** [comment]
the same as me

**Comment by wizart** [comment]
Hi! Same issue 
I use Jest. My OS is Windows.
And use `GitCMD `instead `original CMD console`.

I guess that issue because `path` join with `\` because it Windows. But GitCMD expect `/` and as result tries find `node_modules.binjest`

> const { join } = require("path");
>console.log(join("node_modules",` ".bin", "jest"));

Console output will be
> node_modules\.bin\jest

And try find it in GitCMD
> $ find node_modules\.bin\jest
> find: ‘node_modules.binjest’: No such file or directory

Any ideas for fix?

**Comment by wizart** [comment]
Like Idea is to make function `doesModuleExist` instead `doesFileExist` and use `require.resolve` instead `exists`. 
So NodeJs modules will solve this check instead FS.
@g3offrey  wdyt?

**Comment by JDeuce** [comment]
Same issue here... is there a workaround available to force a specific test runner?

**Comment by nick-gaudreau-omd** [comment]
Same problem with create react app v2 - Typescript. Windows OS.

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080

**Comment by felixjb** [comment]
Hi guys! 
I just fixed the Windows path issue in my version of this project and I think it might have solved this issue too. 
Could you try it out and see whether it really solved it? I would much appreciate it (:

[GitHub repo](https://github.com/felixjb/testify)
[VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=felixjb.testify)

**Comment by smil2k** [comment]
I had the same issue caused by opening the test from a "multi project" folder. There were no node_modules in the root, therefore the runner did not found mocha in the .bin. 

Fixed by opening the project as a multi root setup, so each project was opened as a new root. Then it works perfectly.
