### ISSUE TITLE
Please support *.text.tsx for type script.

### ISSUE THREAD

**Issue by PeikangHu** [g3offrey/javascript-test-runner#3]
When I work under typescript. I am not able to see Run Test button. Could you support typescript as well? Thanks.

**Comment by g3offrey** [comment]
Hi @PeikangHu 
first of all please accept my apologies for the delay 😅 

Thank you for opening an issue 👍 

I understand what you mean, I'll look at this as soon as possible and get back to you once I have a solution 😄

**Comment by g3offrey** [comment]
Thanks to awesome work from @roggenbrot this is finally resolved ! 👏 
I will release a new version including this feature 👍
