### ISSUE TITLE
Test runner not enabled in files containing the spread operator

### ISSUE THREAD

**Issue by aramando** [g3offrey/javascript-test-runner#33]
Hi, this is similar to #10 but with different syntax.

I've found that a spread operator anywhere in a test file prevents the extension from activating and showing the test runner buttons. 

For example this breaks it: 
`const helper = props => anotherHelper({ ...props });`

Incidentally the similar rest operator is _not_ a problem, e.g. 
`const helper = (...args) => anotherHelper();`

**Comment by ddehghan** [comment]
Yeah, this is happening for me as well. with the error

>   ERR This experimental syntax requires enabling the parser plugin: 'objectRestSpread' (75:28)

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080

**Comment by felixjb** [comment]
Hello!
We fixed this in our fork of this extension. [Check it out!](https://github.com/felixjb/testify)
