### ISSUE TITLE
Feature request: not my code

### ISSUE THREAD

**Issue by lonix1** [g3offrey/javascript-test-runner#34]
It would be nice to have a "not my code" [feature for debugging](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome). So we can step over platform code, like "node_modules" etc.

When doing regular debugging this can be enabled in the launch profiles. But with this plugin those profiles aren't used.

Perhaps a new option in the settings, e.g.

````
"javascript-test-runner.skipFiles": [
  "<node_internals>/**/*.js",
  "${workspaceFolder}/node_modules/**/*.js"
]
````

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
