### ISSUE TITLE
Feature request: should work with test.each([])() syntax

### ISSUE THREAD

**Issue by lonix1** [g3offrey/javascript-test-runner#37]
The extension doesn't show codelens items over [`test.each(table)(name, fn, timeout)`](https://jestjs.io/docs/en/api.html#testeachtable-name-fn-timeout) Jest methods.

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
