### ISSUE TITLE
Specify path to test runner

### ISSUE THREAD

**Issue by e0da** [g3offrey/javascript-test-runner#38]
First, thank you. I appreciate your work.

Please allow overriding the test runner path. I want to use `yarn test` as my test runner instead of the detected `node_modules/.bin/jest`. As it stands, this doesn't work with `create-react-app`. This is touched on in #29, but I want to be clear that the problem is that you can't override the test runner. If you could override the test runner, it would completely open up the tool to let people do whatever setup/teardown they need when the out of box experience doesn't work. Right now I could maybe futz with Jest or Babel config and get something to work, but those configs are currently hidden by create-react-app (I haven't "ejected" it, and don't want to). But ideally that'd be moot since I already have a solution for this problem: `yarn test` does everything I need. I'd like to just add something like this to my VSCode user settings.json: 

```json
{  "javascript-test-runner.testRunnerPath": "yarn test" }
```
And in my case, jest is being called underneath so all the rest of the default config can be passed on and work correctly. But today it's just calling the wrong bin. :crying_cat_face:

**Comment by long-hp** [comment]
I want to do the same

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080

**Comment by e0da** [comment]
@g3offrey Well that's ok! Thank you anyway. I appreciate your work.

**Comment by felixjb** [comment]
Hi @justinforce , 
Could you help me understand a little more of how you use `yarn test` in this case? 
I am working on this feature now.
