### ISSUE TITLE
 --testNamePattern="undefined" when ` is used within describe or it

### ISSUE THREAD

**Issue by Romstar** [g3offrey/javascript-test-runner#39]
Hello Guys,

Great VScode plugin, I love it!  There is one issue that isn't allowing my team to utilize this plugin and it is the fact that it expects users to use a single quote to name their describes and it statements.  Our eslint configuration currently requires backticks for all strings.

Example that works: `describe('UPDATE_ANNUAL_INCOME_COMPLETED'`

produces: node_modules/.bin/jest test/unit/client/javascripts/reducers/annual-income-complete-reducer.spec.js **--testNamePattern="UPDATE_ANNUAL_INCOME_COMPLETED"**

Example that doesn't work: describe(\`UPDATE_ANNUAL_INCOME_COMPLETED\`

produces: node_modules/.bin/jest test/unit/client/javascripts/reducers/annual-income-complete-reducer.spec.js **--testNamePattern="undefined"**

Notice the **testnamePattern="undefined"**

Any chance we can get backtick support?

I was able to fix the issue by modifying the codeParser function:

Fix: **testName: ast.tokens[index + 3].value;**

instead of **testName:ast.tokens[index + 2].value;**

**Comment by lonix1** [comment]
It's not just backticks. These also don't work:

````
const testName = "foo";
describe(testName, () => {
  // ...
});

describe(nameof(MyTestClass), () => {                // using nameof TypeScript plugin
  // ...
});
````

So it considers everything within as plain text. I assume this means it is not using a parser when reading the test metadata, just converts to text.

**Comment by Romstar** [comment]
Great find.  This PR will address backticks.  I can debug your situation if you can give me a repo that works with your example and fails with the plug in.

**Comment by lonix1** [comment]
Just a simple variable like I show above would be enough to debug.

That said, please don't waste time on that, because this extension seems to be abandoned. :cry:

Owner hasn't merged anything in ages, or answers issues, so your fix sadly won't be merged.

I left a plea to nominate maintainers (see issues list) and he hasn't responded. If there were at least one contributor/maintainer then we could start fixing this extension. The only choice now is for someone to fork it.

**Comment by Romstar** [comment]
I forked it but I don't want to publish it since it is originally his and without his permission

**Comment by lonix1** [comment]
Its MIT licenced, so technically you are allowed. Also, it's abandoned.

**Comment by lonix1** [comment]
BTW thought you might like this extension I just found: [vscode-jest-runner](https://github.com/firsttris/vscode-jest-runner). It doesn't use codelens, but rather a context menu.

But, it has undocumented shortcuts that you can map - look under files-preferences-shortcuts and look for "jest". There are two shortcuts there. I mapped "shift-1" to run test and "shift-2" to test debug.

Then I press those keys and the test under the cursor is run. And it doesn't suffer the bug that we found in this extension! :smile:

(There is also [this extension](https://marketplace.visualstudio.com/items?itemName=asvetliakov.run-current-test) with more options but I haven't tried it.)

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
