### ISSUE TITLE
Add `run test` for  `context` sections

### ISSUE THREAD

**Issue by jLouzado** [g3offrey/javascript-test-runner#49]
- Only `describe` & `test` sections have the `Run Test` option
- specific `context`'s should be runnable as well

![image](https://user-images.githubusercontent.com/2016685/75131114-7e0e5200-56f7-11ea-947c-d9073aec6527.png)

**Comment by g3offrey** [comment]
Hi @jLouzado 

First of all please accept my apologies for the delay.
Sadly this repository is outdated, and not maintained anymore.

There are forks of this repository I invite you to report your issue on these.
