### ISSUE TITLE
Bug: Occurs on ALL instances of the token "test", not just test files

### ISSUE THREAD

**Issue by nfour** [g3offrey/javascript-test-runner#5]
![](https://i.imgur.com/AoDUbpj.png)

As you can see above, this isn't a test.

The tokenizer needs to check for `function` invokations, and not regexp `/foo/.test()` either.

**Comment by g3offrey** [comment]
Hi @nfour,
First of all thank your for opening an issue for this, indeed, this is really bothering 😓 

I just merged this PR #4 from @ooga 👍 
I guess this should fix your issue, can you please tell me if you still encounter such an issue ?

Thank you 😄

**Comment by dantman** [comment]
I too am getting the behaviour on RegExp `.test`s, my webpack.config.js has a bunch of tests shoved into it.

```js
/* Run Test shows up here */
const isDevelopment = /^(development|production)(-|$)/.test(
	process.env.NODE_ENV
)
	/* Run Test shows up here */
	? /^development(-|$)/.test(process.env.NODE_ENV)
	: BUILD_WATCH;
```

**Comment by g3offrey** [comment]
Hi @dantman,
Thank you for your feedback 😄 
You right. I still have to find a solution for that 😅

**Comment by dantman** [comment]
It's not ideal. But if you need to keep using regexps, it would probably be sufficient to make your regexp for "test" only work when there is a `(` following it and it does not follow any `.`'s or other tokens like `function`.

First draft:
```js
/(?!function\s+|\.\s*)test\s\(/
```

**Comment by g3offrey** [comment]
I am using a tokenizer function, so it should even be easier to test what's the next token and what is his type 👍 
@ooga already improved a lot the detection of real test token in his PR 😄 
But indeed we need to check the next token is "(".
You got a nice solution over here thank you 💯

**Comment by lonix1** [comment]
I am also getting this problem. The codelens actions appear over regex:

````
/foo/.test("foo");
````

**Comment by g3offrey** [comment]
Hello, 

Please accept my apologies for the late answer. 
I published a status about this extension. 😞 
(TL;DR: I won't be able to work on it anymore)

https://github.com/g3offrey/javascript-test-runner/issues/41#issuecomment-497425080
