### ISSUE TITLE
Cannot set ENV vars

### ISSUE THREAD

**Issue by marqu3z** [g3offrey/javascript-test-runner#8]
This extensions is exactly what i need but without the possibility to set at least `NODE_ENV=test` it is impossible to run tests on exisiting projects who make use of environment variables.

**Comment by g3offrey** [comment]
Hi @marqu3z 
Thank you for your contribution and for opening this issue 😄 

You totally right, this should be implemented in the extension 👍 
I'm thinking about adding a configuration field. Something like : `javascript-test-runner.envVars`

I need to think about Windows users too. I guess env vars on this OS are not the same as Unix ones 😅
I add your request in my roadmap 😄

**Comment by marqu3z** [comment]
@g3offrey you use `cross-env` to set env vars across different platforms.

https://www.npmjs.com/package/cross-env

**Comment by g3offrey** [comment]
Hi @marqu3z ! 
This package seems very nice 👍 
I guess I would use your solution while resolving this ticket thanks for your help 😄

**Comment by g3offrey** [comment]
Hi everyone,

I just added a new configuration which permits to set environment variables for test runner.
This will come in the next release (later this month) 😄 🔜
